apiVersion: apps/v1 # which api to use for deployment

kind: Deployment # what kind of service/object do you want to create?
# what would you like to call it - name of the service
metadata:
  name: nginx-deployment # naming deployment
spec:
  selector:
    matchLabels:
      app: nginx #look for this label to match with k8 service
  # Replica set 
  replicas: 3
  #template to use
  template:
    metadata:
      labels:
        app: nginx #this label connects to the service or any other k8 component

    # Container spec
    spec:
      containers:
      - name: nginx
        image: olegf23/tech221-nginx:v1 #use the image from Docker
        ports:
        - containerPort: 90
            